import { Avatar, Button, Card, Select, Statistic, Table, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import DashboardLayout from '../../../components/layout/header/DashboardLayout'
import { useSystemSettings } from '../../../context/SystemSettingsContext'
import { useAuth } from '../../../hooks/useAuth'
import { getSellerOrders } from '../../../services/orderService'
import { getUserDisplayName } from '../../../utils/userDisplay'

const { Text, Title } = Typography
const formatMoney = (value = 0) => `${Number(value || 0).toLocaleString('vi-VN')}đ`
const exportLabels = {
  vi: {
    sheetName: 'Revenue Report',
    workbookTitle: 'GymPro',
    reportTitle: 'BÁO CÁO DOANH THU',
    monthlyReportTitle: 'Báo cáo doanh thu tháng',
    month: 'Tháng',
    year: 'Năm',
    seller: 'Người bán',
    exportDate: 'Ngày xuất',
    totalRevenue: 'Tổng doanh thu',
    totalSold: 'Tổng sản phẩm đã bán',
    productVariants: 'Mẫu sản phẩm có doanh số',
    orderLines: 'Số dòng đơn',
    no: 'STT',
    productImage: 'Ảnh sản phẩm',
    productName: 'Tên sản phẩm',
    variant: 'Phân loại',
    unitPrice: 'Đơn giá',
    quantitySold: 'Số lượng bán',
    revenue: 'Doanh thu',
    finalTotalRevenue: 'Tổng doanh thu cuối',
    footer: 'Được tạo bởi hệ thống GymPro',
  },
  en: {
    sheetName: 'Revenue Report',
    workbookTitle: 'GymPro',
    reportTitle: 'REVENUE REPORT',
    monthlyReportTitle: 'Monthly Revenue Report',
    month: 'Month',
    year: 'Year',
    seller: 'Seller',
    exportDate: 'Export date',
    totalRevenue: 'Total revenue',
    totalSold: 'Total sold',
    productVariants: 'Product variants sold',
    orderLines: 'Order lines',
    no: 'No.',
    productImage: 'Product image',
    productName: 'Product name',
    variant: 'Variant',
    unitPrice: 'Unit price',
    quantitySold: 'Quantity sold',
    revenue: 'Revenue',
    finalTotalRevenue: 'Final total revenue',
    footer: 'Generated by GymPro System',
  },
}

type ProductRef = string | { _id?: string; name?: string; image?: string; images?: string[] }
type OrderItem = {
  productId?: ProductRef
  productName?: string
  productImage?: string
  name?: string
  variant?: { weight?: string }
  weight?: string
  quantity?: number | string
  price?: number | string
}
type SellerOrder = { createdAt?: string; orderDate?: string; updatedAt?: string; items?: OrderItem[] }
type SoldProduct = {
  key: string
  name: string
  image: string
  variant: string
  price: number
  quantity: number
  revenue: number
  orderCount: number
}

const getProductRef = (item: OrderItem) => (item.productId && typeof item.productId === 'object' ? item.productId : undefined)
const getItemId = (item: OrderItem) => getProductRef(item)?._id || item.productId || item.productName || item.name || 'unknown'
const getItemImage = (item: OrderItem) => item.productImage || getProductRef(item)?.image || getProductRef(item)?.images?.[0] || ''
const getItemName = (item: OrderItem, fallback: string) => item.productName || item.name || getProductRef(item)?.name || fallback
const getItemVariant = (item: OrderItem) => item.variant?.weight || item.weight || ''
const getOrderDate = (order: SellerOrder) => order.createdAt || order.orderDate || order.updatedAt
const pad2 = (value: number) => String(value).padStart(2, '0')
const getReportFileStamp = (month: number, year: number) => `${pad2(month)}-${year}`
const currentDate = new Date()
const currentMonth = currentDate.getMonth() + 1
const currentYear = currentDate.getFullYear()
type ExportLanguage = keyof typeof exportLabels

const formatExportMoney = (value: number, lang: ExportLanguage) => {
  const locale = lang === 'en' ? 'en-US' : 'vi-VN'
  const currency = lang === 'en' ? 'VND' : 'VNĐ'
  return `${Number(value || 0).toLocaleString(locale)} ${currency}`
}

const removeVietnameseTones = (text: string): string => text
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .replace(/đ/g, 'd')
  .replace(/Đ/g, 'D')

const toDataUrl = async (url?: string) => {
  if (!url) return ''
  try {
    const response = await fetch(url)
    if (!response.ok || !response.headers.get('content-type')?.startsWith('image/')) return ''
    const blob = await response.blob()
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(String(reader.result || ''))
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  } catch {
    return ''
  }
}

const getImageFormat = (dataUrl: string) => {
  if (dataUrl.startsWith('data:image/jpeg') || dataUrl.startsWith('data:image/jpg')) return 'JPEG'
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP'
  return 'PNG'
}

export default function SellerRevenuePage() {
  const { t, i18n } = useTranslation()
  const { user } = useAuth()
  const { settings } = useSystemSettings()
  const [orders, setOrders] = useState<SellerOrder[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedMonth, setSelectedMonth] = useState(currentMonth)
  const [selectedYear, setSelectedYear] = useState(currentYear)
  const [reportMonth, setReportMonth] = useState(currentMonth)
  const [reportYear, setReportYear] = useState(currentYear)
  const [exporting, setExporting] = useState<'excel' | 'pdf' | ''>('')

  useEffect(() => {
    let cancelled = false

    const fetchOrders = async () => {
      try {
        const res = await getSellerOrders()
        if (!cancelled) setOrders(res.data.data || [])
      } catch (error) {
        if (!cancelled) console.error(error)
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    fetchOrders()

    return () => {
      cancelled = true
    }
  }, [])

  const filteredOrders = useMemo(() => orders.filter((order) => {
    const date = new Date(getOrderDate(order) || '')
    return !Number.isNaN(date.getTime()) && date.getMonth() + 1 === reportMonth && date.getFullYear() === reportYear
  }), [orders, reportMonth, reportYear])

  const soldProducts = useMemo(() => {
    const map = new Map<string, SoldProduct>()

    filteredOrders.forEach((order) => {
      ;(order.items || []).forEach((item) => {
        const variant = getItemVariant(item)
        const key = `${getItemId(item)}::${variant}`
        const quantity = Number(item.quantity || 0)
        const revenue = quantity * Number(item.price || 0)
        const current = map.get(key)

        if (current) {
          current.quantity += quantity
          current.revenue += revenue
          current.orderCount += 1
          return
        }

        map.set(key, {
          key,
          name: getItemName(item, t('seller_dashboard.product_fallback')),
          image: getItemImage(item),
          variant,
          price: Number(item.price || 0),
          quantity,
          revenue,
          orderCount: 1,
        })
      })
    })

    return Array.from(map.values()).sort((a, b) => b.quantity - a.quantity)
  }, [filteredOrders, t])

  const yearOptions = useMemo(() => {
    const years = new Set([currentYear, selectedYear, reportYear])
    orders.forEach((order) => {
      const date = new Date(getOrderDate(order) || '')
      if (!Number.isNaN(date.getTime())) years.add(date.getFullYear())
    })
    return Array.from(years).sort((a, b) => b - a).map((year) => ({ label: String(year), value: year }))
  }, [orders, selectedYear, reportYear])

  const monthOptions = Array.from({ length: 12 }, (_, index) => ({ label: String(index + 1), value: index + 1 }))

  const totalSold = soldProducts.reduce((sum, item) => sum + item.quantity, 0)
  const totalRevenue = soldProducts.reduce((sum, item) => sum + item.revenue, 0)
  const totalOrderLines = soldProducts.reduce((sum, item) => sum + item.orderCount, 0)
  const sellerName = getUserDisplayName(user, t('seller_dashboard.seller_fallback'))
  const reportPeriod = `${pad2(reportMonth)}/${reportYear}`
  const hasReportData = soldProducts.length > 0

  const getExportContext = () => {
    const lang: ExportLanguage = i18n.resolvedLanguage?.startsWith('en') || i18n.language?.startsWith('en') ? 'en' : 'vi'
    return {
      lang,
      labels: exportLabels[lang],
      reportDate: new Date().toLocaleString(lang === 'en' ? 'en-US' : 'vi-VN'),
    }
  }

  const handleApply = () => {
    setReportMonth(selectedMonth)
    setReportYear(selectedYear)
  }

  const handleExportExcel = async () => {
    setExporting('excel')
    try {
      const ExcelJS = (await import('exceljs')).default
      const { lang, labels, reportDate } = getExportContext()
      const workbook = new ExcelJS.Workbook()
      const sheet = workbook.addWorksheet(labels.sheetName)
      const tableBorder = {
        top: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
        left: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
        bottom: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
        right: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
      }

      sheet.columns = [
        { width: 8 },
        { width: 28 },
        { width: 14 },
        { width: 18 },
        { width: 16 },
        { width: 16 },
        { width: 18 },
      ]
      sheet.pageSetup = {
        orientation: 'landscape',
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        margins: { left: 0.4, right: 0.4, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
      }

      sheet.mergeCells('A1:G1')
      sheet.getCell('A1').value = labels.workbookTitle
      sheet.getCell('A1').font = { bold: true, size: 20, color: { argb: 'FFB6462F' } }
      sheet.getCell('A1').alignment = { horizontal: 'center' }
      sheet.getRow(1).height = 28
      sheet.mergeCells('A2:G2')
      sheet.getCell('A2').value = labels.monthlyReportTitle
      sheet.getCell('A2').font = { bold: true, size: 16 }
      sheet.getCell('A2').alignment = { horizontal: 'center' }
      sheet.getRow(2).height = 24

      sheet.addRow([])
      sheet.addRow([labels.seller, sellerName])
      sheet.addRow([`${labels.month}/${labels.year}`, reportPeriod])
      sheet.addRow([labels.exportDate, reportDate])
      sheet.addRow([])
      sheet.addRow([labels.totalRevenue, formatExportMoney(totalRevenue, lang)])
      sheet.addRow([labels.totalSold, totalSold])
      sheet.addRow([labels.productVariants, soldProducts.length])
      sheet.addRow([labels.orderLines, totalOrderLines])
      sheet.addRow([])

      for (let rowNumber = 4; rowNumber <= 10; rowNumber += 1) {
        sheet.getCell(`A${rowNumber}`).font = { bold: true }
        sheet.getCell(`A${rowNumber}`).alignment = { horizontal: 'left', vertical: 'middle' }
        sheet.getCell(`B${rowNumber}`).alignment = { horizontal: 'left', vertical: 'middle' }
      }

      const headerRow = sheet.addRow([labels.no, labels.productName, labels.variant, labels.unitPrice, labels.quantitySold, labels.orderLines, labels.revenue])
      sheet.views = [{ state: 'frozen', ySplit: headerRow.number }]
      headerRow.font = { bold: true }
      headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } }
      headerRow.height = 24
      headerRow.eachCell((cell) => {
        cell.alignment = { horizontal: 'center', vertical: 'middle' }
        cell.border = tableBorder
      })

      soldProducts.forEach((item, index) => {
        const row = sheet.addRow([
          index + 1,
          item.name,
          item.variant || '-',
          formatExportMoney(item.price, lang),
          item.quantity,
          item.orderCount,
          formatExportMoney(item.revenue, lang),
        ])
        row.height = 22
        row.eachCell((cell, colNumber) => {
          cell.border = tableBorder
          cell.alignment = {
            horizontal: colNumber === 2 ? 'left' : [1, 3, 5, 6].includes(colNumber) ? 'center' : 'right',
            vertical: 'middle',
            wrapText: colNumber === 2,
          }
        })
      })
      const totalRow = sheet.addRow(['', '', '', '', '', '', formatExportMoney(totalRevenue, lang)])
      sheet.mergeCells(`A${totalRow.number}:F${totalRow.number}`)
      sheet.getCell(`A${totalRow.number}`).value = labels.finalTotalRevenue
      totalRow.font = { bold: true }
      totalRow.height = 24
      for (let colNumber = 1; colNumber <= 7; colNumber += 1) {
        const cell = sheet.getCell(totalRow.number, colNumber)
        cell.border = tableBorder
        cell.alignment = { horizontal: 'right', vertical: 'middle' }
      }

      const buffer = await workbook.xlsx.writeBuffer()
      const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
      const link = document.createElement('a')
      link.href = URL.createObjectURL(blob)
      link.download = `GymPro-Revenue-${getReportFileStamp(reportMonth, reportYear)}.xlsx`
      link.click()
      URL.revokeObjectURL(link.href)
      message.success(t('seller_dashboard.export_success'))
    } catch (error) {
      console.error(error)
      message.error(t('seller_dashboard.export_failed'))
    } finally {
      setExporting('')
    }
  }

  const handleExportPdf = async () => {
    setExporting('pdf')
    try {
      const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')])
      const { lang, labels, reportDate } = getExportContext()
      const pdfText = (value: string | number) => lang === 'vi' ? removeVietnameseTones(String(value)) : String(value)
      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
      const logoData = await toDataUrl(settings.general.logoUrl)
      if (logoData) {
        doc.addImage(logoData, getImageFormat(logoData), 14, 10, 18, 18)
      } else {
        doc.setFillColor(182, 70, 47)
        doc.roundedRect(14, 10, 18, 18, 3, 3, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(11)
        doc.text('GP', 19, 22)
      }

      doc.setTextColor(24, 24, 27)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(18)
      doc.text(pdfText(labels.reportTitle), 38, 17)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.text(pdfText(`${labels.seller}: ${sellerName}`), 38, 24)
      doc.text(pdfText(`${labels.month}/${labels.year}: ${reportPeriod}`), 38, 30)
      doc.text(pdfText(`${labels.exportDate}: ${reportDate}`), 210, 24)

      const summary = [
        [pdfText(labels.totalRevenue), formatMoney(totalRevenue)],
        [pdfText(labels.totalSold), String(totalSold)],
        [pdfText(labels.productVariants), String(soldProducts.length)],
        [pdfText(labels.orderLines), String(totalOrderLines)],
      ]
      summary.forEach(([label, value], index) => {
        const x = 14 + index * 68
        doc.setFillColor(248, 250, 252)
        doc.roundedRect(x, 40, 62, 20, 3, 3, 'F')
        doc.setTextColor(100, 116, 139)
        doc.setFontSize(8)
        doc.text(pdfText(label), x + 4, 48)
        doc.setTextColor(15, 23, 42)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(11)
        doc.text(value, x + 4, 56)
        doc.setFont('helvetica', 'normal')
      })

      autoTable(doc, {
        startY: 68,
        head: [[labels.no, labels.productName, labels.variant, labels.unitPrice, labels.quantitySold, labels.orderLines, labels.revenue].map(pdfText)],
        body: soldProducts.map((item, index) => [index + 1, pdfText(item.name), pdfText(item.variant || '-'), formatMoney(item.price), item.quantity, item.orderCount, formatMoney(item.revenue)]),
        foot: [['', '', '', '', '', pdfText(labels.finalTotalRevenue), formatMoney(totalRevenue)]],
        styles: { font: 'helvetica', fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [182, 70, 47], textColor: 255, fontStyle: 'bold' },
        footStyles: { fillColor: [243, 244, 246], textColor: [15, 23, 42], fontStyle: 'bold' },
      })

      const pageCount = doc.getNumberOfPages()
      for (let page = 1; page <= pageCount; page += 1) {
        doc.setPage(page)
        doc.setFontSize(9)
        doc.setTextColor(100, 116, 139)
        doc.text(pdfText(labels.footer), 14, 200)
        doc.text(`${page}/${pageCount}`, 278, 200)
      }

      doc.save(`GymPro-Revenue-${getReportFileStamp(reportMonth, reportYear)}.pdf`)
      message.success(t('seller_dashboard.export_success'))
    } catch (error) {
      console.error(error)
      message.error(t('seller_dashboard.export_failed'))
    } finally {
      setExporting('')
    }
  }

  const columns: ColumnsType<SoldProduct> = [
    { title: 'STT', width: 70, render: (_value, _record, index) => index + 1 },
    {
      title: t('seller_dashboard.product_image'),
      dataIndex: 'image',
      width: 110,
      render: (image: string, item) => <Avatar shape="square" size={48} src={image || undefined}>{!image && item.name.charAt(0)}</Avatar>,
    },
    { title: t('seller_dashboard.product_name'), dataIndex: 'name', render: (value: string) => <Text strong>{value}</Text> },
    { title: t('seller_dashboard.variant'), dataIndex: 'variant', render: (value: string) => value || '-' },
    { title: t('seller_dashboard.unit_price'), dataIndex: 'price', render: (value: number) => formatMoney(value) },
    { title: t('seller_dashboard.quantity_sold'), dataIndex: 'quantity', sorter: (a, b) => a.quantity - b.quantity },
    { title: t('seller_dashboard.order_lines'), dataIndex: 'orderCount' },
    { title: t('seller_dashboard.revenue'), dataIndex: 'revenue', render: (value: number) => formatMoney(value), sorter: (a, b) => a.revenue - b.revenue },
  ]

  return (
    <DashboardLayout>
      <div className="space-y-4 p-4 max-[640px]:p-0">
        <div className="dashboard-hero rounded-[28px] border border-[var(--gs-border)]" style={{ background: 'linear-gradient(135deg, color-mix(in srgb, var(--theme-accent, #b6462f) 14%, transparent), transparent)' }}>
          <p className="text-xs uppercase tracking-[0.3em] text-[var(--gs-text-soft)]">Seller</p>
          <h1 className="mt-3 text-4xl font-semibold text-[var(--gs-text)] max-[767px]:text-2xl">{t('seller_dashboard.revenue_report')}</h1>
        </div>
        <Card className="max-[640px]:border-0 max-[640px]:bg-transparent">
          <div className="grid gap-3 lg:grid-cols-[1fr_1fr_auto_auto_auto]">
            <div className="space-y-1">
              <Text type="secondary">{t('seller_dashboard.month')}</Text>
              <Select className="w-full" value={selectedMonth} options={monthOptions} onChange={setSelectedMonth} />
            </div>
            <div className="space-y-1">
              <Text type="secondary">{t('seller_dashboard.year')}</Text>
              <Select className="w-full" value={selectedYear} options={yearOptions} onChange={setSelectedYear} />
            </div>
            <Button className="self-end" type="primary" onClick={handleApply}>{t('seller_dashboard.apply')}</Button>
            <Button className="self-end" onClick={handleExportExcel} loading={exporting === 'excel'} disabled={loading || !hasReportData || Boolean(exporting)}>{t('seller_dashboard.export_excel')}</Button>
            <Button className="self-end" onClick={handleExportPdf} loading={exporting === 'pdf'} disabled={loading || !hasReportData || Boolean(exporting)}>{t('seller_dashboard.export_pdf')}</Button>
          </div>
        </Card>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <Card><Statistic title={t('seller_dashboard.total_revenue')} value={formatMoney(totalRevenue)} /></Card>
          <Card><Statistic title={t('seller_dashboard.total_sold')} value={totalSold} /></Card>
          <Card><Statistic title={t('seller_dashboard.product_variants_sold')} value={soldProducts.length} /></Card>
          <Card><Statistic title={t('seller_dashboard.order_lines')} value={totalOrderLines} /></Card>
        </div>
        <Card className="max-[640px]:border-0 max-[640px]:bg-transparent">
          <Title level={4} style={{ marginTop: 0 }}>{t('seller_dashboard.sold_products_title')} - {reportPeriod}</Title>
          <div className="member-scroll-x">
            <Table rowKey="key" loading={loading} dataSource={soldProducts} columns={columns} pagination={{ pageSize: 10 }} scroll={{ x: 980 }} />
          </div>
        </Card>
      </div>
    </DashboardLayout>
  )
}
