import type { ComponentType } from 'react'
import {
  AccountBookOutlined,
  AppstoreOutlined,
  ArrowDownOutlined,
  BarChartOutlined,
  CalendarOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  DollarOutlined,
  ExceptionOutlined,
  FileDoneOutlined,
  GroupOutlined,
  LineChartOutlined,
  ProfileOutlined,
  ReloadOutlined,
  RiseOutlined,
  RocketOutlined,
  ShoppingOutlined,
  ShopOutlined,
  StarOutlined,
  SwapOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  UserOutlined,
  WalletOutlined,
  WarningOutlined,
} from '@ant-design/icons'

const ICON_MAP: Record<string, ComponentType<any>> = {
  finance: WalletOutlined,
  members: TeamOutlined,
  pt: ThunderboltOutlined,
  booking: CalendarOutlined,
  shop: ShopOutlined,
  system: AppstoreOutlined,
  revenue: DollarOutlined,
  orders: ProfileOutlined,
  refund: ExceptionOutlined,
  avg: LineChartOutlined,
  new: RocketOutlined,
  active: CheckCircleOutlined,
  renew: ReloadOutlined,
  change: SwapOutlined,
  cancel: WarningOutlined,
  checkin: FileDoneOutlined,
  session: ClockCircleOutlined,
  rating: StarOutlined,
  success: CheckCircleOutlined,
  pending: ClockCircleOutlined,
  class: GroupOutlined,
  waiting: ClockCircleOutlined,
  product: ShoppingOutlined,
  seller: UserOutlined,
  return: ArrowDownOutlined,
  users: TeamOutlined,
  admin: BarChartOutlined,
  staff: AccountBookOutlined,
}

export default function KpiIcon({ name }: { name: string }) {
  const Icon = ICON_MAP[name] || RiseOutlined
  return <Icon />
}
